name: Install, build and test
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Install-Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm t
